/**
 * OgcService: Interoperability engine complying with OGC (WMS/WCS) and CF-1.8 Conventions.
 * Enables integration with GeoServer, THREDDS, ERDDAP, and INCOIS Ocean Data Portals.
 */
export class OgcService {
  /**
   * Generates standard OGC WMS 1.3.0 GetCapabilities XML document
   */
  static generateWmsCapabilities(metadata) {
    const latB = metadata.lat_bounds || [0.0, 25.0];
    const lonB = metadata.lon_bounds || [50.0, 95.0];

    const layersXml = Object.entries(metadata.variables || {})
      .map(([k, v]) => `
      <Layer queryable="1">
        <Name>${v.name}</Name>
        <Title>${v.long_name} (${v.units})</Title>
        <Abstract>INCOIS 3D Ocean Model Field - ${v.long_name}</Abstract>
        <CRS>CRS:84</CRS>
        <CRS>EPSG:4326</CRS>
        <EX_GeographicBoundingBox>
          <westBoundLongitude>${lonB[0]}</westBoundLongitude>
          <eastBoundLongitude>${lonB[1]}</eastBoundLongitude>
          <southBoundLatitude>${latB[0]}</southBoundLatitude>
          <northBoundLatitude>${latB[1]}</northBoundLatitude>
        </EX_GeographicBoundingBox>
        <Dimension name="elevation" units="meters" default="0">-2000/0/24</Dimension>
        <Dimension name="time" units="ISO8601" default="${metadata.time_steps?.[0] || '2026-09-01T00:00:00Z'}">${metadata.time_steps?.join(',') || ''}</Dimension>
      </Layer>`)
      .join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<WMS_Capabilities version="1.3.0" xmlns="http://www.opengis.net/wms" xmlns:xlink="http://www.w3.org/1999/xlink">
  <Service>
    <Name>WMS</Name>
    <Title>INCOIS 3D Ocean Model Web Map Service</Title>
    <Abstract>Operational CF-compliant 3D Ocean State Simulation for North Indian Ocean</Abstract>
    <ContactInformation>
      <ContactPersonPrimary>
        <ContactPerson>INCOIS Ocean Modeling Group</ContactPerson>
        <ContactOrganization>Indian National Centre for Ocean Information Services (MoES)</ContactOrganization>
      </ContactPersonPrimary>
    </ContactInformation>
  </Service>
  <Capability>
    <Request>
      <GetCapabilities><Format>text/xml</Format></GetCapabilities>
      <GetMap><Format>image/png</Format><Format>image/jpeg</Format></GetMap>
    </Request>
    <Layer>
      <Title>INCOIS Indian Ocean 3D Sandbox</Title>
      <CRS>EPSG:4326</CRS>
      ${layersXml}
    </Layer>
  </Capability>
</WMS_Capabilities>`;
  }

  /**
   * Export in-situ observation network to standardized GeoJSON FeatureCollection (RFC 7946)
   */
  static exportGeoJson(instruments = []) {
    const features = instruments.map((inst) => {
      const lat = inst.latitude || inst.waypoints?.[0]?.latitude || 0;
      const lon = inst.longitude || inst.waypoints?.[0]?.longitude || 0;
      return {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [lon, lat, -(inst.profile?.[0]?.depth || 0)],
        },
        properties: {
          platform_id: inst.platform_id,
          wmo_id: inst.wmo_id || inst.mission_id,
          instrument_type: inst.instrument_type,
          basin: inst.basin,
          timestamp: inst.timestamp || inst.start_time,
          profile_levels: inst.profile?.length || inst.waypoints?.length || 0,
        },
      };
    });

    return JSON.stringify({
      type: 'FeatureCollection',
      features,
      metadata: {
        title: 'INCOIS In-Situ Marine Observing System Export',
        generatedAt: new Date().toISOString(),
        institution: 'INCOIS (Ministry of Earth Sciences)',
      },
    }, null, 2);
  }

  /**
   * Generate downloadable CF-1.8 NetCDF metadata text header
   */
  static generateCfMetadataReport(metadata) {
    return `# Climate and Forecast (CF) Metadata Report
# Standard: NetCDF-CF Convention v1.8
# Institution: Indian National Centre for Ocean Information Services (INCOIS), Hyderabad, India
# Domain: North Indian Ocean (Lat: ${metadata.lat_bounds?.[0]}N - ${metadata.lat_bounds?.[1]}N, Lon: ${metadata.lon_bounds?.[0]}E - ${metadata.lon_bounds?.[1]}E)
# Depth Range: 0m to 2000m (${metadata.depth_levels || 24} vertical sigma/log-spaced levels)
# Time Steps: ${metadata.time_steps?.length || 8} regular 6-hourly operational forecasts

## Active Variables:
${Object.entries(metadata.variables || {})
  .map(([k, v]) => `  * ${k.toUpperCase()}: ${v.long_name} [${v.units}] (Min: ${v.min_val}, Max: ${v.max_val})`)
  .join('\n')}

Generated by INCOIS 3D Ocean Sandbox Interoperability Module.
`;
  }
}
