export const SCIENCE_STORIES = [
  {
    id: 'arabian-sea-monsoon',
    title: 'Arabian Sea Southwest Monsoon & Coastal Upwelling',
    region: 'West Coast of India / Arabian Sea Basin',
    badge: 'Ocean Dynamics',
    summary: 'Discover how the Southwest Monsoon reverses the Somali and West India coastal currents, driving nutrient-rich cold upwelling water to the surface along Kerala and Goa to boost India’s marine fisheries.',
    steps: [
      {
        title: '1. Pre-Monsoon Surface Heating (Gujarat & North Arabian Sea)',
        narration: 'Prior to the summer monsoon onset, intense solar radiation creates sea surface temperatures exceeding 30 degrees Celsius across the northern Arabian Sea and Gulf of Kutch, priming atmospheric convective systems.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 25,
        isIsosurface: false,
        camera: { pos: [65, 80, -210], target: [45, 32, -85] },
      },
      {
        title: '2. Ekman Coastal Upwelling (Kerala, Goa & Karnataka)',
        narration: 'Alongshore south-westerly monsoon winds push surface waters offshore via Ekman transport. This draws cold, nutrient-rich 18 degrees Celsius water from the deep thermocline upward along the coasts of Kerala, Goa, and Karnataka.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 35,
        isIsosurface: true,
        isovalue: 0.55,
        camera: { pos: [60, 50, -185], target: [25, 20, -92] },
      },
      {
        title: '3. Phytoplankton Bloom (Chlorophyll-a Spike)',
        narration: 'The upwelled nitrate and phosphate trigger explosive phytoplankton blooms. Chlorophyll concentrations spike above 2.5 milligrams per cubic meter along the southwest coast of India, creating the primary nursery grounds for Indian fisheries.',
        variable: 'chlorophyll',
        palette: 'chlorophyll',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [55, 65, -195], target: [30, 24, -90] },
      },
    ],
  },
  {
    id: 'bay-of-bengal-salinity',
    title: 'Bay of Bengal Freshwater Barrier Layer & Cyclones',
    region: 'East Coast of India / Head Bay of Bengal',
    badge: 'Salinity & Cyclones',
    summary: 'Massive monsoon river discharge from the Ganges and Brahmaputra creates a buoyant, low-salinity surface lens that inhibits vertical mixing, trapping heat in a barrier layer that rapidly intensifies tropical cyclones.',
    steps: [
      {
        title: '1. Low-Salinity Surface River Plume (Ganges Delta to Odisha)',
        narration: 'The Ganges, Brahmaputra, and Mahanadi rivers discharge over one thousand cubic kilometers of freshwater. This creates a buoyant, low-salinity lens below 31 PSU across the northern Bay of Bengal and Bengal plume.',
        variable: 'salt',
        palette: 'haline',
        exaggeration: 25,
        isIsosurface: false,
        camera: { pos: [-5, 75, -210], target: [-2, 30, -93] },
      },
      {
        title: '2. Barrier Layer Formation & Cyclone Supercharging',
        narration: 'The sharp vertical salinity gradient forms an impenetrable barrier layer. Cold subsurface water cannot mix upward, insulating heat above 28 degrees Celsius and supercharging passing tropical cyclones like Fani and Amphan.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 35,
        isIsosurface: true,
        isovalue: 0.35,
        camera: { pos: [-10, 55, -195], target: [8, 22, -94] },
      },
    ],
  },
  {
    id: 'oxygen-minimum-zone',
    title: 'North Indian Ocean Oxygen Minimum Zone (OMZ)',
    region: 'Arabian Sea & Bay of Bengal Intermediate Depths',
    badge: 'Biogeochemistry',
    summary: 'High primary productivity and semi-enclosed basin circulation create one of the world’s thickest oxygen minimum zones at 150m to 800m depth, governing nitrogen cycles and marine habitats.',
    steps: [
      {
        title: '1. Euphotic Zone Oxygen Saturation (Indian Basin Overview)',
        narration: 'At the sea surface, air-sea gas exchange and photosynthesis maintain dissolved oxygen above 200 micromoles per kilogram in the upper 30 meters, supporting rich pelagic ecosystems.',
        variable: 'oxygen',
        palette: 'deep',
        exaggeration: 25,
        isIsosurface: false,
        camera: { pos: [32, 60, -230], target: [21, 34, -91] },
      },
      {
        title: '2. The Severe Intermediate OMZ Core (150m – 800m)',
        narration: 'Between 150 and 800 meters, sinking organic detritus is consumed by bacteria, exhausting dissolved oxygen down to suboxic levels below 20 micromoles per kilogram. INCOIS OMNI buoys and bio-Argo floats monitor this critical layer.',
        variable: 'oxygen',
        palette: 'deep',
        exaggeration: 40,
        isIsosurface: true,
        isovalue: 0.15,
        camera: { pos: [45, 45, -185], target: [30, 26, -90] },
      },
    ],
  },
  {
    id: 'somali-jet-currents',
    title: 'Somali Jet & North Indian Ocean Boundary Currents',
    region: 'Western Arabian Sea & Equatorial Indian Ocean',
    badge: 'Current Vectors',
    summary: 'Explore the powerful low-level Findlater Jet that drives the Somali Current northward with surface velocities exceeding 2.5 m/s, generating the Great Whirl and reversing coastal boundary currents.',
    steps: [
      {
        title: '1. Findlater Jet & The Great Whirl Eddy',
        narration: 'During the Southwest Monsoon, strong low-level atmospheric winds accelerate the Somali Current, creating intense anticyclonic eddies known as the Great Whirl in the western Arabian Sea.',
        variable: 'u',
        palette: 'viridis',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [85, 40, -195], target: [45, 12, -88] },
      },
      {
        title: '2. East & West India Coastal Boundary Currents',
        narration: 'The East India Coastal Current and West India Coastal Current reverse seasonally, steering mass and heat transport between the Arabian Sea and the Bay of Bengal around Kanyakumari.',
        variable: 'u',
        palette: 'viridis',
        exaggeration: 35,
        isIsosurface: false,
        camera: { pos: [30, 55, -210], target: [20, 26, -92] },
      },
    ],
  },
];
