export const SCIENCE_STORIES = [
  {
    id: 'arabian-sea-monsoon',
    title: 'Arabian Sea Monsoon Currents & Coastal Upwelling',
    region: 'Arabian Sea / West Coast of India',
    badge: 'Ocean Dynamics',
    summary: 'Discover how the Southwest Monsoon reverses the Somali and West India coastal currents, driving nutrient-rich cold upwelling water to the surface and boosting marine fisheries.',
    steps: [
      {
        title: '1. Summer Pre-Monsoon Surface Heating',
        narration: 'Welcome to the INCOIS 3D Ocean Exploration. Prior to the summer monsoon onset, intense solar radiation creates sea surface temperatures exceeding 30 degrees Celsius across the northern Arabian Sea.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [0, 160, 240], target: [0, -20, 0] },
      },
      {
        title: '2. Coastal Upwelling & Thermocline Shoaling',
        narration: 'Alongshore south-westerly monsoon winds push surface waters offshore via Ekman transport. This draws cold, nutrient-rich 18 degrees Celsius water from the deep thermocline upward along the coasts of Kerala, Goa, and Karnataka.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 45,
        isIsosurface: true,
        isovalue: 0.55,
        camera: { pos: [-70, 70, 110], target: [-30, -15, 0] },
      },
      {
        title: '3. Biological Productivity Explosion (Chlorophyll-a)',
        narration: 'The upwelled nitrate and phosphate trigger explosive phytoplankton blooms. Chlorophyll concentrations spike along the southwest coast of India, creating the primary nursery grounds for Indian fisheries.',
        variable: 'chlorophyll',
        palette: 'chlorophyll',
        exaggeration: 35,
        isIsosurface: false,
        camera: { pos: [-50, 90, 130], target: [-20, -10, 0] },
      },
    ],
  },
  {
    id: 'bay-of-bengal-salinity',
    title: 'Bay of Bengal Freshwater Barrier Layer & Cyclones',
    region: 'Bay of Bengal / East Coast of India',
    badge: 'Salinity & Cyclones',
    summary: 'Massive monsoon river discharge creates a thin, low-salinity surface lens that inhibits vertical mixing, trapping heat in a barrier layer that rapidly intensifies tropical cyclones.',
    steps: [
      {
        title: '1. Low-Salinity Surface River Plume',
        narration: 'The Ganges, Brahmaputra, and Godavari rivers discharge over one thousand cubic kilometers of freshwater. This creates a buoyant, low-salinity lens below 32 PSU across the northern Bay of Bengal.',
        variable: 'salt',
        palette: 'haline',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [80, 140, 160], target: [45, -15, 0] },
      },
      {
        title: '2. Barrier Layer Formation & Cyclone Fuel',
        narration: 'The sharp vertical salinity gradient forms an impenetrable barrier layer. Cold subsurface water cannot mix upward, insulating heat above 28 degrees Celsius and supercharging passing monsoon cyclones.',
        variable: 'salt',
        palette: 'haline',
        exaggeration: 50,
        isIsosurface: true,
        isovalue: 0.35,
        camera: { pos: [65, 80, 100], target: [35, -20, 0] },
      },
    ],
  },
  {
    id: 'oxygen-minimum-zone',
    title: 'North Indian Ocean Oxygen Minimum Zone (OMZ)',
    region: 'Arabian Sea & Bay of Bengal Intermediate Depths',
    badge: 'Biogeochemistry',
    summary: 'High primary productivity and restricted ventilation create one of the worlds thickest oxygen minimum zones at 150m to 800m depth, driving global nitrogen cycling.',
    steps: [
      {
        title: '1. Euphotic Zone Oxygen Saturation',
        narration: 'At the sea surface, air-sea gas exchange and photosynthesis maintain dissolved oxygen above 200 micromoles per kilogram, supporting vibrant marine biodiversity.',
        variable: 'oxygen',
        palette: 'deep',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [-30, 150, 180], target: [-10, -20, 0] },
      },
      {
        title: '2. The Severe Intermediate OMZ Core',
        narration: 'Between 150 and 800 meters, sinking organic detritus is consumed by bacteria, exhausting dissolved oxygen down to suboxic levels below 20 micromoles per kilogram. INCOIS OMNI buoys continuously monitor this critical layer.',
        variable: 'oxygen',
        palette: 'deep',
        exaggeration: 45,
        isIsosurface: true,
        isovalue: 0.15,
        camera: { pos: [0, 90, 120], target: [0, -30, 0] },
      },
    ],
  },
];
